export const LOGIN_USER_REQUEST = 'login_user_request';
export const LOGIN_USER_SUCCESS = 'login_user_success';
export const LOGIN_USER_ERROR = 'login_user_error';
export const REGISTER_USER_REQUEST = 'register_user_request';
export const REGISTER_USER_SUCCESS = 'register_user_success';
export const REGISTER_USER_ERROR = 'register_user_error';
export const LOGOUT_USER_REQUEST = 'logout_user_request';
export const LOGOUT_USER_SUCCESS = 'logout_user_success';
export const LOGOUT_USER_ERROR = 'logout_user_error';
export const NOMINATE_MOVIE_REQUEST = 'nominate_movie_request';
export const NOMINATE_MOVIE_SUCCESS = 'nominate_movie_success';
export const NOMINATE_MOVIE_ERROR = 'nominate_movie_error';
export const REMOVE_NOMINATE_MOVIE_REQUEST = 'remove_nominate_movie_request';
export const REMOVE_NOMINATE_MOVIE_SUCCESS = 'remove_nominate_movie_success';
export const REMOVE_NOMINATE_MOVIE_ERROR = 'remove_nominate_movie_error';
export const RESET_SUCCESS = 'reset_success';
export const RESET_ERROR ='reset_error'
export const AUTH_USER_SUCCESS='auth_user_success'
export const AUTH_USER_ERROR = 'auth_user_error';
export const FETCH_MOVIES_DATA_REQUEST = 'fetch_movies_data_request';
export const FETCH_MOVIES_DATA_SUCCESS = 'fetch_movies_data_success';
export const BLACKLIST_MOVIE_SUCCESS = 'blacklist_movie_success';
export const BLACKLIST_MOVIE_FAILURE = 'blacklist_movie_failure';
export const BLACKLIST_MOVIE_FETCH = 'blacklist_movie_fetch';